### ISSUE TITLE
Can't edit wiki

### ISSUE THREAD

**Issue by kameko** [jphp-compiler/jphp#227]
Hi me and my friends were making funny memes on the wiki and now we can't edit it plesse fix allah loves you bye

**Comment by wowse** [comment]
:+1:

**Comment by SerafimArts** [comment]
This is due to revisions of this user https://github.com/goodmind (they are there more than 10). I had to lock the wiki, I hope temporarily:
https://github.com/jphp-compiler/jphp/wiki/_DOWNLOAD/_compare/eac9417%5E...eac9417
https://github.com/jphp-compiler/jphp/wiki/Home/_compare/73b384c%5E...73b384c
etc...

**Comment by SerafimArts** [comment]
Please complain about his behavior, after locking his account - I think no more threats of spam.

**Comment by kameko** [comment]
hi yes goodmind is banned now, please unlock wiki. allah loves you, peace and legs
